name: Final Deploy
on:
  push:
    branches: [main]
jobs:
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Inject Key
        run: sed -i "s/__API_KEY_PLACEHOLDER__/${{ secrets.API_KEY }}/g" index.html
      - name: Push to Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages